#!/bin/bash

Tar_path=/home/daquitree/Downloads/yujin_ocs-0.8.2

set $(ls -l $Tar_path | grep "^d" | awk '{print $9}' |grep -wv "yujin_ocs")

Module_path="yujin_ocs"
Hash_name="yujin_ocs.hash"
Pkg_version="0.8.2"
Archive_path="https://github.com/yujinrobot/yujin_ocs/archive"

echoGConfigIn()
{
echo source \"package/rockchip/ros/$Module_path/$1/Config.in\" >> Config.in
}

touchConfigIn()
{
typeset -u upper
upper="$1"
cat >$1/Config.in <<!FUNKY!	
config BR2_PACKAGE_$upper
    bool "$1"
    help
      "$1" 
!FUNKY!
}

copyRenameHash()
{
cp $Module_path/$Hash_name $1/$1.hash
}

editMK()
{
typeset -u upper
upper="$1"
cat >$1/$1.mk <<!FUNKY!
#default to KINETIC
${upper}_VERSION = $Pkg_version

${upper}_SOURCE = \$(${upper}_VERSION).tar.gz
${upper}_SITE = $Archive_path
${upper}_SUBDIR = $1

#${upper}_DEPENDENCIES = bash findutils

\$(eval \$(catkin-package))

!FUNKY!
}

while [ "$1" != "" ]; do
	mkdir $1
	echoGConfigIn $1
	touchConfigIn $1
	copyRenameHash $1
	editMK $1
	#rm -rf $1
	shift
done

exit 0

