#!/bin/bash

Target=kobuki_core 						# should check
Pkg_version="0.7.10"     					# should check
Pkg_type=tar.gz							# should check
Path=/home/daquitree/Downloads					# should check
Tarball_path=$Path/${Target}-${Pkg_version}.${Pkg_type}		# should check
Dir_path=$Path/${Target}-${Pkg_version}

Archive_path="https://github.com/yujinrobot/kobuki_core/archive" 	# should check

set $(ls -l $Dir_path | grep "^d" | awk '{print $9}')

echoGConfigIn()
{
echo source \"package/rockchip/ros/$Target/$1/Config.in\" >> Config.in #should check
}

touchConfigIn()
{
typeset -u upper
upper="$1"
cat >$1/Config.in <<!FUNKY!	
config BR2_PACKAGE_$upper
    bool "$1"
    help
      "$1" 
!FUNKY!
}

copyRenameHash()
{
cat >$1/$1.hash <<!FUNKY!	
md5 $(md5sum $Tarball_path | cut -d " " -f 1) ${Pkg_version}.tar.gz
!FUNKY!

}

editMK()
{
typeset -u upper
upper="$1"
cat >$1/$1.mk <<!FUNKY!
#default to KINETIC
${upper}_VERSION = $Pkg_version

${upper}_SOURCE = \$(${upper}_VERSION).tar.gz
${upper}_SITE = $Archive_path
${upper}_SUBDIR = $1

#${upper}_DEPENDENCIES = 

\$(eval \$(catkin-package))

!FUNKY!
}


touchGlobalFiles()
{
#touch global .mk
echo "include \$(sort \$(wildcard package/rockchip/ros/$Target/*/*.mk))" > $Target.mk

#touch global Config.in
typeset -u upper
upper="$Target"
cat >Config.in <<!FUNKY!	
config BR2_PACKAGE_${upper}_SET
    bool "$Target"
    depends on BR2_PACKAGE_HOST_CATKIN
    help
      "$Target DaQui Marked" 

if BR2_PACKAGE_${upper}_SET
!FUNKY!
}


#main
touchGlobalFiles
while [ "$1" != "" ]; do
	mkdir $1
	echoGConfigIn $1
	touchConfigIn $1
	copyRenameHash $1
	editMK $1
	#rm -rf $1
	shift
done

echo endif >> Config.in #finish Config.in

exit 0

